### ISSUE TITLE
[bug] 当relative_link: true 时，图片路径会错。

### ISSUE THREAD

**Issue by arrayofstar** [yiyungent/hexo-asset-img#14]
如题，正常hexo g生成的网页中，图片路径应该是

<img src="/2024/09/18/My-New-Post/test.jpg" class="" title="test">

当设置 relative_link: true 时，图片路径开头少一个“/”。如下：

<img src="2024/09/18/My-New-Post/test.jpg" class="" title="test">

**Comment by History-exe** [comment]
我也遇到类似的问题。
一开始按照readme说明，在vscode中将插入的图片如此写入`![描述](文章名/图片名.png)`，但是部署之后在网页端并未正确显示图片。
之后我在“文章名”前添加了“本目录标记“，也就是"`./`"。即变为”`![描述](./文章名/图片名.png)`，并在_config.yml中开启相对链接`relative_link: true`之后，图片就可以在网页中正常显示了。

**Comment by History-exe** [comment]
> 我也出现问题了，，，，突然间，怎么这样了。。。到底是哪里的问题。。。插件版本并没变啊

要不你先按照我的办法弄吧，我的解决办法就在你回答的上面。

**Comment by History-exe** [comment]
> > 我也出现问题了，，，，突然间，怎么这样了。。。到底是哪里的问题。。。插件版本并没变啊
> 
> 报下 hexo 版本，以及本插件版本，以及配置文件，最好再给个 demo

hexo版本：hexo-cli: 4.3.2

插件版本：hexo-asset-img@1.2.0

使用主题：https://github.com/auroral-ui/hexo-theme-aurora

示例：示例不知道提供什么比较好，我的博客目前都是添加`./`插入图片的，具体麻烦去我的博客看一下

https://history-exe.github.io/post/2025-05-14-21-09

配置文件：
<details>
  <summary>点击展开代码</summary>

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: /post/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
syntax_highlighter: highlight.js
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: aurora

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:History-exe/History-exe.github.io.git
  branch: main
```

**Comment by yiyungent** [comment]
> > > 我也出现问题了，，，，突然间，怎么这样了。。。到底是哪里的问题。。。插件版本并没变啊
> > 
> > 
> > 报下 hexo 版本，以及本插件版本，以及配置文件，最好再给个 demo
> 
> hexo版本：hexo-cli: 4.3.2
> 
> 插件版本：hexo-asset-img@1.2.0
> 
> 使用主题：https://github.com/auroral-ui/hexo-theme-aurora
> 
> 示例：示例不知道提供什么比较好，我的博客目前都是添加`./`插入图片的，具体麻烦去我的博客看一下
> 
> https://history-exe.github.io/post/2025-05-14-21-09
> 
> 配置文件：
> 
> 点击展开代码
> ```
> # Hexo Configuration
> ## Docs: https://hexo.io/docs/configuration.html
> ## Source: https://github.com/hexojs/hexo/
> 
> # Site
> title: Hexo
> subtitle: ''
> description: ''
> keywords:
> author: John Doe
> language: en
> timezone: ''
> 
> # URL
> ## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
> url: http://example.com
> permalink: /post/:title.html
> permalink_defaults:
> pretty_urls:
>   trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
>   trailing_html: true # Set to false to remove trailing '.html' from permalinks
> 
> # Directory
> source_dir: source
> public_dir: public
> tag_dir: tags
> archive_dir: archives
> category_dir: categories
> code_dir: downloads/code
> i18n_dir: :lang
> skip_render:
> 
> # Writing
> new_post_name: :title.md # File name of new posts
> default_layout: post
> titlecase: false # Transform title into titlecase
> external_link:
>   enable: true # Open external links in new tab
>   field: site # Apply to the whole site
>   exclude: ''
> filename_case: 0
> render_drafts: false
> post_asset_folder: true
> relative_link: true
> future: true
> syntax_highlighter: highlight.js
> highlight:
>   enable: false
>   line_number: true
>   auto_detect: false
>   tab_replace: ''
>   wrap: true
>   hljs: false
> prismjs:
>   enable: false
>   preprocess: true
>   line_number: true
>   tab_replace: ''
> 
> # Home page setting
> # path: Root path for your blogs index page. (default = '')
> # per_page: Posts displayed per page. (0 = disable pagination)
> # order_by: Posts order. (Order by date descending by default)
> index_generator:
>   path: ''
>   per_page: 10
>   order_by: -date
> 
> # Category & Tag
> default_category: uncategorized
> category_map:
> tag_map:
> 
> # Metadata elements
> ## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
> meta_generator: true
> 
> # Date / Time format
> ## Hexo uses Moment.js to parse and display date
> ## You can customize the date format as defined in
> ## http://momentjs.com/docs/#/displaying/format/
> date_format: YYYY-MM-DD
> time_format: HH:mm:ss
> ## updated_option supports 'mtime', 'date', 'empty'
> updated_option: 'mtime'
> 
> # Pagination
> ## Set per_page to 0 to disable pagination
> per_page: 10
> pagination_dir: page
> 
> # Include / Exclude file(s)
> ## include:/exclude: options only apply to the 'source/' folder
> include:
> exclude:
> ignore:
> 
> # Extensions
> ## Plugins: https://hexo.io/plugins/
> ## Themes: https://hexo.io/themes/
> theme: aurora
> 
> # Deployment
> ## Docs: https://hexo.io/docs/one-command-deployment
> deploy:
>   type: git
>   repository: git@github.com:History-exe/History-exe.github.io.git
>   branch: main
> ```


问问，什么情况下需要 `relative_link: true`, 是主题要求吗？我看 hexo 配置这个默认是 false, 按照 hexo 文档，这个当改为 true, 确实就应当变为相对路径，也就导致部署后变成你那样了

https://hexo.io/zh-cn/docs/configuration.html#文章

`relative_link` 把链接改为与根目录的相对位址 `false`

**Comment by History-exe** [comment]
> 开了相对链接的可以试试下面
> 
> post_asset_folder: true
> marked:
>   prependRoot: true
>   postAsset: true
> 
> 以及还可以试下旧版本 hexo-asset-img: 1.1.0, 新的 1.2.0 与 旧版本机制大不同

一、关于hexo版本，如下：
"hexo": "^7.3.0",
"hexo-asset-img": "^1.2.0"

二、关于为什么开启`relative_link: true`
印象中是好像是为了把每篇文章的图片集中到一个单独的文件夹才这么设置的。
也好像是想实现在vscode中实时预览图片。**使本地编辑文章、本地网页预览和网站部署后都可以显示图片**，具体参考的哪篇文章，现在回想不起来了。

即在本地编辑文章时，想实现如下效果

![Image](https://github.com/user-attachments/assets/2ae9b806-338d-4ed4-96e9-51c7bc750e30)

三、关于修改建议，所做的尝试：

尝试1
如下设置后，结果见表格1

```
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
```

表格1
|测试编号|文章内源码|本地编辑文章|本地网页测试|本地网页生成的源码
|-----|--------|-------|------|------|
|测试1|`![](./2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片可见|图片不可见|`<img src="/./2021-11-06-22-00/AE_graveAfternoon.jpg">`|
|测试2|`![](/2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片不可见|图片不可见|`<img src="/2021-11-06-22-00/AE_graveAfternoon.jpg">`|
|测试3|`![](2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片可见|图片不可见|`<img src="/2021-11-06-22-00/AE_graveAfternoon.jpg">`|
|测试4|`![](/source/_posts/2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片可见|图片不可见|`<img src="/source/_posts/2021-11-06-22-00/AE_graveAfternoon.jpg">`|

尝试2
如下设置后，结果见表格2，与表格1的区别只有`relative_link: true`

```
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: true
```

表格2
|测试编号|文章内源码|本地编辑文章|本地网页测试|本地网页生成的源码
|-----|--------|-------|------|------|
|测试5|`![](./2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片可见|图片可见|`<img src="./2021-11-06-22-00/AE_graveAfternoon.jpg">`|
|测试6|`![](/2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片不可见|图片不可见|`<img src="/2021-11-06-22-00/AE_graveAfternoon.jpg">`|
|测试7|`![](2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片可见|图片可见|`<img src="2021-11-06-22-00/AE_graveAfternoon.jpg">`|
|测试8|`![](/source/_posts/2021-11-06-22-00/AE_graveAfternoon.jpg )`|图片可见|图片不可见|`<img src="/source/_posts/2021-11-06-22-00/AE_graveAfternoon.jpg">`|

三、总结
在我使用aurora主题，需求为**本地编辑文章、本地网页预览和网站部署后都可以显示图片**加上**每篇文章的图片集中到一个单独的文件夹**时，需要一个必备条件，两种插入图片方法可以满足。

必备条件
即配置文件必须如下。其中这两项应该为根本，`relative_link: true`和`post_asset_folder: true`
```
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: true
```

两种插入图片的方法，即按照测试5和测试7的方式
测试5的方式：`![](./2021-11-06-22-00/AE_graveAfternoon.jpg )`
测试7的方式：`![](2021-11-06-22-00/AE_graveAfternoon.jpg )`
